# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-sitemap"
gem "minima", "~> 2.5"

# Local development - use the gem from parent directory
group :jekyll_plugins do
  gem "jekyll-documents", path: ".."
end
