name: Publish Gem

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Build gem
        run: gem build jekyll-documents.gemspec

      - name: Publish to RubyGems
        run: |
          mkdir -p ~/.gem
          cat << EOF > ~/.gem/credentials
          ---
          :rubygems_api_key: ${RUBYGEMS_API_KEY}
          EOF
          chmod 0600 ~/.gem/credentials
          gem push *.gem
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}

      - name: Publish to GitHub Packages
        run: |
          cat << EOF > ~/.gem/credentials
          ---
          :github: Bearer ${GITHUB_TOKEN}
          EOF
          chmod 0600 ~/.gem/credentials
          gem push --key github --host https://rubygems.pkg.github.com/gundestrup *.gem
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
